### ISSUE TITLE
NSComparisonResult vs. CFComparisonResult

### ISSUE THREAD

**Issue by alexmnps** [brokaw/SBDataStructures#1]
Compiler warning on [line 63 of SBBinaryHeapPriorityQueue.m](https://github.com/brokaw/SBDataStructures/blob/master/SBDataStructures/SBBinaryHeapPriorityQueue.m#L63):

> Warning:(63, 12) implicit conversion from enumeration type 'NSComparisonResult' (aka 'enum NSComparisonResult') to different enumeration type 'CFComparisonResult' (aka 'enum CFComparisonResult')

Do they evaluate to the same raw types? If so, then I guess we should cast explicitly.

---

Thanks for this lib, BTW, SBBinaryHeapPriorityQueue works great.

**Comment by brokaw** [comment]
The values are the same. The underlying types are different and need to be cast. Here are the relevant typedefs.

```
typedef CF_ENUM(CFIndex, CFComparisonResult) {
    kCFCompareLessThan = -1L,
    kCFCompareEqualTo = 0,
    kCFCompareGreaterThan = 1
};

#if __LLP64__
typedef signed long long CFIndex;
#else
typedef signed long CFIndex;
#endif

typedef NS_ENUM(NSInteger, NSComparisonResult) {NSOrderedAscending = -1L, NSOrderedSame, NSOrderedDescending};

#if __LP64__ || (TARGET_OS_EMBEDDED && !TARGET_OS_IPHONE) || TARGET_OS_WIN32 || NS_BUILD_32_LIKE_64
typedef long NSInteger;
#else
typedef int NSInteger;
#endif
```
